#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S4,              GyroSensor,          sensorI2CCustom)
#pragma config(Motor,  motorA,          RightLight,    tmotorNormal, openLoop)
#pragma config(Motor,  motorC,          LeftLight,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     LeftUpperDrive, tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     LeftLowerDrive, tmotorNormal, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     RightUpperDrive, tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     RightLowerDrive, tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     LiftMotor,     tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     BeltMotor,     tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    ArmLeft,              tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    ArmRight,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    BackFlap,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define TEAM_NUMBER 3717

#include "..\Common\Autonomous Template.h"
#include "Includes\Game Specific\Get Over It 2010\Left Bridge.h"
#include "Includes\Game Specific\Get Over It 2010\Left Mountain.h"
#include "Includes\Game Specific\Get Over It 2010\Left Dispense.h"
#include "Includes\Game Specific\Get Over It 2010\Left Balance.h"
#include "Includes\Game Specific\Get Over It 2010\Defense.h"
#include "Includes\Game Specific\Get Over It 2010\Left Score.h"


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////// TASK MAIN //////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
task main()
{
  int Mission = 1;  // 1 = Left Bridge, 2 = Left Mountain, 3 = Left Dispense, 4 = Left Balance, 5 = Defense

  InitializeRobot("LEFT");		// Perform all required initialization sub-routine

  bDisplayDiagnostics = false;
  eraseDisplay();

  nxtDisplayCenteredBigTextLine(2, "Select");
  nxtDisplayCenteredBigTextLine(4, "Mission");

  wait1Msec(250);

  while ( nNxtButtonPressed != 3 )
  {
    if ( nNxtButtonPressed == 1 && time1[T1] > 500 && Mission < 6)
    {
      Mission++;
      time1[T1] = 0;
    }
    else if ( nNxtButtonPressed == 2 && time1[T1] > 500 && Mission > 1 )
    {
      Mission--;
      time1[T1] = 0;
    }

    if ( Mission == 1 )
    {
      nxtDisplayCenteredBigTextLine(2, "Left");
      nxtDisplayCenteredBigTextLine(4, "Score?");
    }
    else if ( Mission == 2 )
    {
      nxtDisplayCenteredBigTextLine(2, "Left");
      nxtDisplayCenteredBigTextLine(4, "Mountain?");
    }
    else if ( Mission == 3 )
    {
      nxtDisplayCenteredBigTextLine(2, "Left");
      nxtDisplayCenteredBigTextLine(4, "Dispense?");
    }
    else if ( Mission == 4 )
    {
      nxtDisplayCenteredBigTextLine(2, "Left");
      nxtDisplayCenteredBigTextLine(4, "Balance?");
    }
    else if ( Mission == 5 )
    {
      nxtDisplayCenteredBigTextLine(3, "Defense");
    }
    else if ( Mission == 6 )
    {
      nxtDisplayCenteredBigTextLine(2, "Left");
      nxtDisplayCenteredBigTextLine(4, "Bridge?");
    }

    wait1Msec(25);
    eraseDisplay();
  }

  nxtDisplayCenteredBigTextLine(3, "CONFIRMED");

  wait1Msec(750);

  eraseDisplay();

  if ( Mission == 3 )
  {
    Left_Dispense();        // Dispenses Left Side Dispenser, will ask user for height of
    return;
  }
  else if ( Mission == 5 )
  {
    Defense();
    return;
  }
  else if ( Mission == 1 )
  {
    Left_Score();
    return;
  }

  bDisplayDiagnostics = true;

  waitForStart();

  if ( Mission == 6 )
  {
    Left_Bridge();
  }
  else if ( Mission == 2 )
  {
    Left_Mountain();
  }
  else if ( Mission == 4 )
  {
    Left_Balance();
  }
}
