#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorJ1,       tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorJ2,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorJ3,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    motorJ4,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    motorJ5,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define TEAM_NUMBER 3717
#include "../3717/Includes/TeamConfig.h"
#include "../Common/Control/ArmControl.h"

long pTime = 0;

bool goneUp = false;

task main()
{
	nMotorEncoder[motorJ1] = 0;
	int posOutput = 0;
	int goalPosition = -10;
	while (true)
	{
    posOutput = updatePosPID(90, goalPosition);
    updateSpeedPID(posOutput);
    if(nPgmTime - pTime > 4000)
    {
      if(goalPosition > -90 && !goneUp)
      {
      	goalPosition -= 10;
      }
      else if(goalPosition == -90 && !goneUp)
      {
      	goneUp = true;
      }
      if(goalPosition < 90 && goneUp)
      {
      	goalPosition += 10;
      }
      else if(goalPosition == 90 && goneUp)
      {
      	goneUp = false;
      }
      pTime = nPgmTime;
    }
    wait1Msec(20);
	}
}
