#pragma config(Hubs,  S2, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S2_C1_1,     motorD,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S2_C1_2,     motorE,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S2_C2_1,     motorF,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S2_C2_2,     motorG,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S2_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S2_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "commonConfig.h"
#include "pidControl.h"

long pTimeLoop = 0;
long pMoveMotorTime = 0;

task main() {
	initArm();
	armMotor1.currentGoalPosDegrees = 90;
	armMotor2.currentGoalPosDegrees = 90;
	armMotor1.currentGoalSpeedDegreesPerSecond = 90;
	armMotor2.currentGoalSpeedDegreesPerSecond = 90;
	while (true) {
		updateArm();

		if(nPgmTime - pMoveMotorTime > 10000)
    {
			armMotor1.currentGoalPosDegrees += 90;
			armMotor2.currentGoalPosDegrees += 90;
			pMoveMotorTime = nPgmTime;
		}

		while(nPgmTime - pTimeLoop < 20) {
			wait1Msec(1);
		}
		pTimeLoop = nPgmTime;
	}
}
