#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     driveMotor,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	int deltaTicks = 0;
	int totalTicks = 0;
	int lastTicks = 0;
	nMotorEncoder[driveMotor] = 0;
	motor[driveMotor] = 50;
	while (true) {
		totalTicks = nMotorEncoder[driveMotor];
		deltaTicks = totalTicks - lastTicks;
		//writeDebugStream("Total Ticks: %d  \n Delta Ticks: %d \n\n", totalTicks, deltaTicks * 100 * 4);
		nxtDisplayTextLine(3, "D/Sec: %d", (int)((((float)deltaTicks * 360.0)/1440.0) * 10.0));
		nxtDisplayTextLine(4, "Ticks: %d", deltaTicks);
		lastTicks = totalTicks;
		wait1Msec(100);
	}
}
