#pragma config(Hubs,  S3, HTMotor,  none,     none,     none)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S3_C1_1,     testMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S3_C1_2,     motorE,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[testMotor] = 100;
	long pTime = 0;
	long lastEncoderReading = 0;
	while(true)
	{
			nxtDisplayCenteredTextLine(4, "RPM: %f", ((((float)abs(nMotorEncoder[testMotor]) - (float)abs(lastEncoderReading)) / 4) / 360) * 3000);
			lastEncoderReading = nMotorEncoder[testMotor];
			while(nPgmTime - pTime < 20)
			{
			}
			pTime = nPgmTime;
	}
}
