#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S4, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S2_C1_1,     Turntable,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S2_C1_2,     LeftDrive,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S2_C2_1,     ArmJ2,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S2_C2_2,     ArmJ1,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S4_C1_1,     Nothing,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     RightDrive,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S4_C2_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S4_C2_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S4_C2_3,    servo3,               tServoStandard)
#pragma config(Servo,  srvo_S4_C2_4,    servo4,               tServoStandard)
#pragma config(Servo,  srvo_S4_C2_5,    servo5,               tServoStandard)
#pragma config(Servo,  srvo_S4_C2_6,    servo6,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  nMotorEncoder[RightDrive] = 0;
  nMotorEncoder[LeftDrive] = 0;
  wait1Msec(50);
  while(true)
  	{
    nxtDisplayTextLine(1, "LD %d", nMotorEncoder[LeftDrive]);
    nxtDisplayTextLine(3, "RD %d", nMotorEncoder[RightDrive]);
    wait1Msec(10);
  nMotorEncoder[ArmJ1] = 0;
  nMotorEncoder[ArmJ2] = 0;
  wait1Msec(50);
  while(true)
  	{
    nxtDisplayTextLine(1, "armJ1 %d", nMotorEncoder[ArmJ1]);
    nxtDisplayTextLine(3, "armJ2 %d", nMotorEncoder[ArmJ2]);
    wait1Msec(10);
  }
}
}
