#pragma config(Sensor, S3,     IRsensor1,      sensorI2CCustom)
#pragma config(Sensor, S4,     IRsensor2,      sensorI2CCustom)
#pragma config(Motor,  motorA,          right_motor,   tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,          left_motor,    tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define TEAM_NUMBER 4590
#include "JoystickDriver.c"
#include "../4590/Includes/TeamConfig.h"
#include "../Common/Control/SensorTask.h"
task main()
{
	bDisplayDiagnostics = false;
	int straightValue1 = 2;
	int straightValue2 = 8;
	int error;
	int basePower = 50;
	int Kp = 1;
	float Ki = 0.01;
	int Kd = 0.1;
	int prevError = 0;
	int irReading1;
	int irReading2;
	int integral = 0;
	int turnPower = 0;
	int derivative = 0;
	clearDebugStream();
	while(true)
	{
		irReading1 = ReadIR1();
		irReading2 = ReadIR2();
		int errorSample1 = irReading1 - straightValue1;
		int errorSample2 = irReading2 - straightValue2;

		error = errorSample1 + errorSample2;
		integral += error;
		derivative = error - prevError;
		turnPower = error*Kp + Ki*integral + Kd*derivative;
		nxtDisplayTextLine(1, "error = %i", error);
		writeDebugStreamLine("error = %i", error);
		nxtDisplayTextLine(2, " prevError = %i", prevError);
		writeDebugStreamLine("prevError = %i", error);
		nxtDisplayTextLine(4, "IRReading = %i", irReading1);
		writeDebugStreamLine("IR1 = %i", irReading1);
		nxtDisplayTextLine(5, "IR2Reading = %i", irReading2);
		writeDebugStreamLine("IR2 = %i", irReading2);
		//motor[left_motor] = basePower + turnPower;
		//motor[right_motor] = basePower - turnPower;
		prevError = error;
	}
}
