#pragma config(Sensor, S1,     IRsensor1,      sensorI2CCustom)
#pragma config(Sensor, S4,     IRsensor2,      sensorI2CCustom)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          left_motor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          right_motor,   tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define TEAM_NUMBER 4590
#include "JoystickDriver.c"
#include "../4590/Includes/TeamConfig.h"
#include "../Common/Control/SensorTask.h"
task main()
{
	bDisplayDiagnostics = false;
	int straightValue = 5;
	int error;
	int basePower = 50;
	int Kp = 10;
	float Ki = 0.01;
	int Kd = 3;
	int prevError = 0;
	int irReading = 0;
	int integral = 0;
	int turnPower = 0;
	int derivative = 0;
	while(true)
	{
		irReading = ReadIR1();
		error = ReadIR1() - straightValue;
		if(error == -5)
		{
			if(prevError >= 0)
			{
				error = 5;
			}
			else
			{
			}
		}
		integral = integral + error;
		derivative = error - prevError;
		turnPower = error*Kp + Ki*integral + Kd*derivative;
		nxtDisplayTextLine(2, "error = %i", error);
		nxtDisplayTextLine(4, " prevError = %i", prevError);
		nxtDisplayTextLine(6, "IRReading = %i", irReading);
		//motor[left_motor] = basePower + turnPower;
		//motor[right_motor] = basePower - turnPower;

		prevError = error;
	}
}
