#pragma config(Hubs,  S4, HTServo,  none,     none,     none)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Servo,  srvo_S4_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S4_C1_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S4_C1_3,    servo3,               tServoStandard)
#pragma config(Servo,  srvo_S4_C1_4,    servo4,               tServoStandard)
#pragma config(Servo,  srvo_S4_C1_5,    servo5,               tServoStandard)
#pragma config(Servo,  srvo_S4_C1_6,    servo6,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
		{
			servo[servo4] = 90;
	servo[servo1] = 90;
	servo[servo3] = 180;
	servo[servo5] = 0;
	servo[servo2] = 90;
}}
