#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Servo,  srvo_S2_C1_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
  while(true) {
	  servo[servo1] = 0;
	  servo[servo2] = 0;
	  servo[servo3] = 0;
	  servo[servo4] = 0;
	  servo[servo5] = 0;
	  servo[servo6] = 0;
	  wait1Msec(2000);
	  servo[servo1] = 80;
	  servo[servo2] = 80;
	  servo[servo3] = 80;
	  servo[servo4] = 80;
	  servo[servo5] = 80;
	  servo[servo6] = 80;
	  wait1Msec(2000);
  }
}
