#pragma config(Hubs,  S3, HTMotor,  HTMotor,  HTServo,  HTServo)
#pragma config(Hubs,  S4, HTMotor,  none,     none,     none)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S3_C1_1,     RRD,           tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S3_C1_2,     SPIN,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S3_C2_1,     RFD,           tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S3_C2_2,     motorE,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S4_C1_1,     LFD,           tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S4_C1_2,     LRD,           tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S3_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S3_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S3_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S3_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S3_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S3_C3_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S3_C4_1,    servo7,               tServoNone)
#pragma config(Servo,  srvo_S3_C4_2,    servo8,               tServoNone)
#pragma config(Servo,  srvo_S3_C4_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S3_C4_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S3_C4_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S3_C4_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{

int yaxis = 0;
int xaxis = 0;

int yaxis2 = 0;

int leftDrive = 0;
int rightDrive = 0;


	while (true) {
		getJoystickSettings(joystick);
	  yaxis = joystick.joy1_y2;
	  yaxis2 = joystick.joy1_y1;
    xaxis = joystick.joy1_x1;

		if (abs(xaxis) < 10) {
			xaxis = 0;
		}
    motor[SPIN] = xaxis;
    if (abs(yaxis) < 10) {
    	yaxis = 0;
    }
		motor[RRD] = yaxis;
		motor[RFD] = yaxis;
		motor[LRD] = yaxis;
		motor[LFD] = yaxis;

		/*motor[RRD] = -yaxis;
		motor[RFD] = -yaxis;
		motor[LRD] = -yaxis2;
		motor[LFD] = -yaxis2;*/

		/*getJoystickSettings(joystick);
	  leftDrive = joystick.joy1_y1;
    rightDrive = joystick.joy1_y2;
    motor[SPIN] = 0;
    motor[RFD] = rightDrive;
    motor[RRD] = rightDrive;
    motor[LFD] = leftDrive;
    motor[LRD] = leftDrive;*/

	}
}
