#define FORWARD_COLLECT_POWER  100
#define REVERSE_COLLECT_POWER -65

#define NO_POWER 							 0

#define SERVO_BACK_STOW_POSIITON     35
#define SERVO_BACK_COLLECT_POSITION  200

#define SERVO_FRONT_STOW_POSITION 0
#define SERVO_FRONT_COLLECT_POSITION 200
