#define FORWARD_COLLECT_POWER  100
#define REVERSE_COLLECT_POWER -100
#define NO_POWER 							 0

#define SERVO_BACK_STOW_POSIITON     75
#define SERVO_BACK_COLLECT_POSITION  250

#define SERVO_FRONT_STOW_POSITION 0
#define SERVO_FRONT_COLLECT_POSITION 200
