#define LIFT_COLLECT_ENCODER 0
#define LIFT_LOW_ENCODER		  6594
#define LIFT_MID_ENCODER		  12021
#define LIFT_HIGH_ENCODER     18242
#define LIFT_CENTER_ENCODER   28800
#define LIFT_TARGET_ERROR    (BASE_ENCODER_TICK_1_REV)
#define LIFT_MOTOR_POWER     100
#define LIFT_HOLD_POWER			 15
