#pragma config(Hubs,  S3, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S4, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S3_C1_1,     Turntable,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S3_C1_2,     RightDrive,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S3_C2_1,     ArmJ2,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S3_C2_2,     ArmJ1,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S4_C1_1,     Nothing,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     LeftDrive,     tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S4_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S4_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S4_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S4_C2_4,    servo4,               tServoStandard)
#pragma config(Servo,  srvo_S4_C2_5,    servo5,               tServoStandard)
#pragma config(Servo,  srvo_S4_C2_6,    servo6,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define TEAM_NUMBER 5076

#pragma systemFile            // this eliminates warning for "unreferenced" functions

#include "../Common/GlobalDefines.h"
#include "JoystickDriver.c"
#include "Includes/TeamConfig.h"
#include "../Common/Control/ArmKinematics.h"
#include "../Common/Control/ArmControl.h"

task main()
{
	long pTime = 0;
	int motorGoalPosJ1 = 0;
	float motorGoalPosJ2 = ARM_J2_JCS_OFFSET_DEG;
	float motorGoalPos = 0;
	int servoGoalPos = 0;
	int servoDelta = 35;
	servo[servo4] = 0;
	servo[servo6] = 180;
	servo[servo5] = 180;

	eraseDisplay();

	nxtDisplayTextLine(3, "initializing...");

	StartTask(ArmControlTask);
	wait1Msec(2000);

	while (true)
	{
		getJoystickSettings(joystick);
		long g1 = ReadArmJointGoal(1);
		long g2 = ReadArmJointGoal(2);
		long g3 = ReadArmJointGoal(3);
		long g4 = ReadArmJointGoal(4);
		long g5 = ReadArmJointGoal(5);

		long a1 = ReadArmJointAngle(1);
		long a2 = ReadArmJointAngle(2);
		long a3 = ReadArmJointAngle(3);
		long a4 = ReadArmJointAngle(4);
		long a5 = ReadArmJointAngle(5);

		nxtDisplayTextLine(0, "J1: %d/%d/%d", g1, a1, (g1-a1));
		nxtDisplayTextLine(1, "J2: %d/%d/%d", g2, a2, (g2-a2));
		nxtDisplayTextLine(2, "J3: %d/%d/%d", g3, a3, (g3-a3));
		nxtDisplayTextLine(3, "J4: %d/%d (%d)", g4, a4, servoDelta);
		nxtDisplayTextLine(4, "J5: %d/%d (%d)", g5, a5, servoDelta);

motorGoalPosJ1 = 0;
motorGoalPosJ2 = -90;



		ArmJoint_MoveToPosAtRate(1, motorGoalPosJ1, 90.0);
		ArmJoint_MoveToPosAtRate(2, motorGoalPosJ2, 90.0);

		wait1Msec(5);
	}
}

/*	while (true)
{
getJoystickSettings(joystick);
long g1 = ReadArmJointGoal(1);
long g2 = ReadArmJointGoal(2);
long g3 = ReadArmJointGoal(3);
long e1 = ReadJointEncoder(1);
long e2 = ReadJointEncoder(2);
long e3 = ReadJointEncoder(3);
nxtDisplayTextLine(0, "J1 goal: %d", e1);
nxtDisplayTextLine(1, "  error: %d", g1-e1);
nxtDisplayTextLine(2, "J2 goal: %d", e2);
nxtDisplayTextLine(3, "  error: %d", g2-e2);
nxtDisplayTextLine(4, "J3 goal: %d", servoGoalPos);
nxtDisplayTextLine(5, "  error: %d", g3-e3);
nxtDisplayTextLine(6, "J4/5 delta: %d", servoDelta);

if (joystick.joy1_y1 > 10)
{
motorGoalPosJ1 = 900;
}
else if (joystick.joy1_y1 < -10)
{
motorGoalPosJ1 = -900;
}
else
{
ArmJoint_Hold(1);
motorGoalPosJ1 = ReadArmJointAngle(1);
}


if (joy1Btn(01))
{
motorGoalPosJ2 = 900;
}
else if (joy1Btn(02))
{
motorGoalPosJ2 = -900;
}
else
{
ArmJoint_Hold(2);
motorGoalPosJ2 = ReadArmJointAngle(2);
}

if (joy1Btn(02))//claw open
{
servo[servo4] += 5;
servo[servo6] -= 5;
}


if (joy1Btn(01))//claw closed
{
servo[servo4] -= 5;
servo[servo6] += 5;
}


if (joystick.joy1_TopHat == 0)//wrist up
{
servo[servo5] += 5;
}


if (joystick.joy1_TopHat == 4)//wrist down
{
servo[servo5] -= 5;
}

if (joy1Btn(07))//turntable
{
motor[Turntable] = 20;
}
else if (joy1Btn(08))
{
motor[Turntable] = -20;
}
else
{
motor[Turntable] = 0;
}



if(joystick.joy2_y2 <= 8 && joystick.joy2_y2 >= -8)
{
motor[RightDrive] = 0;
}
else
{
motor[RightDrive] = joystick.joy2_y2*-1;
}
if(joystick.joy1_y1 <= 8 && joystick.joy2_y1 >= -8)
{
motor[LeftDrive] = 0;
}
else
{
motor[LeftDrive] = joystick.joy2_y1*1;
}*/





//ArmJoint_MoveToPosAtRate(1, 0, 40.0);//motorGoalPosJ1
//ArmJoint_MoveToPosAtRate(2, 30, 40.0);//motorGoalPosJ2
//ArmJoint_MoveToPosAtRate(3, motorGoalPos, 90.0);
//ArmJoint_MoveToPosAtRate(4, servoGoalPos, 90.0);
//ArmJoint_MoveToPosAtRate(5, servoGoalPos, 90.0);


/*if(nPgmTime - pTime > 10000)
{
motorGoalPos += 90;

servoGoalPos += servoDelta;
if ( servoGoalPos > 180 )
{
servoDelta *= -1;
}
else if ( servoGoalPos < 0 )
{
servoDelta *= -1;
}

pTime = nPgmTime;
}*/

//wait1Msec(5);
//}
//}
