#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S4, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S2_C1_1,     ArmJ2,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S2_C1_2,     ArmJ1,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S2_C2_1,     Turntable,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     LeftDrive,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S4_C1_1,     Nothing,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     RightDrive,    tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S4_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S4_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S4_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S4_C2_4,    servo4,               tServoStandard)
#pragma config(Servo,  srvo_S4_C2_5,    servo5,               tServoStandard)
#pragma config(Servo,  srvo_S4_C2_6,    servo6,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define TEAM_NUMBER 5076

#pragma systemFile            // this eliminates warning for "unreferenced" functions

#include "../Common/GlobalDefines.h"
#include "JoystickDriver.c"
#include "Includes/TeamConfig.h"
#include "../Common/Control/ArmKinematics.h"
#include "../Common/Control/ArmControl.h"



task main()
{
	long Sa = 90;
	long S_offset_a = 0;

	servo[servo4] = 90;
	servo[servo6] = 90;
	servo[servo3] = 180;
	servo[servo5] = 0;



	eraseDisplay();

	nxtDisplayTextLine(3, "initializing...");

	StartTask(ArmControlTask);



	waitForStart();

	long g1 = ReadArmJointGoal(1);
	long g2 = ReadArmJointGoal(2);
	long g3 = ReadArmJointGoal(3);
	long g4 = ReadArmJointGoal(4);
	long g5 = ReadArmJointGoal(5);

	long a1 = ReadArmJointAngle(1);
	long a2 = ReadArmJointAngle(2);
	long a3 = ReadArmJointAngle(3);
	long a4 = ReadArmJointAngle(4);
	long a5 = ReadArmJointAngle(5);


	nxtDisplayTextLine(0, "J1: %d/%d/%d", g1, a1, (g1-a1));
	nxtDisplayTextLine(1, "J2: %d/%d/%d", g2, a2, (g2-a2));
	nxtDisplayTextLine(2, "J3: %d/%d/%d", g3, a3, (g3-a3));

#define servocontrol
	{
		Sa = 90-a1-10;
		servo[servo4] = Sa;
	}

	motor[LeftDrive] = 100;
	motor[RightDrive] = -100;
	wait1Msec(2100);
	motor[LeftDrive] = -100;
	motor[RightDrive] = -100;
	wait1Msec(500);
	motor[LeftDrive] = 100;
	motor[RightDrive] = -100;
	wait1Msec(700);
	motor[LeftDrive] = 100;
	motor[RightDrive] = 100;
	wait1Msec(750);
	servocontrol;
	ArmJoint_MoveToPosAtRate(1, -20, 90.0);
	servocontrol;
	wait1Msec(1000);
	servocontrol;
	ArmJoint_MoveToPosAtRate(1, -10, 90.0);
	servocontrol;
	wait1Msec(1000);
	servocontrol;
	ArmJoint_MoveToPosAtRate(1, 0, 90.0);
	servocontrol;
	wait1Msec(1000);
	servocontrol;
	motor[LeftDrive] = -100;
	motor[RightDrive] = 100;
	wait1Msec(500);


}
