#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     LeftDrive_1,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     LeftDrive_2,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     RightDrive_1,  tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     RightDrive_2,  tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//comment

//comment

#define TEAM_NUMBER 5076

#include "../Common/GlobalDefines.h"
#include "JoystickDriver.c"
#include "Includes/TeamConfig.h"
#include "Autonomous.h"
