#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     LeftDrive_1,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     LeftDrive_2,   tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     RightDrive_1,  tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     RightDrive_2,  tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     ArmJ1,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     ArmExtention,  tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define TEAM_NUMBER 5076

#pragma systemFile            // this eliminates warning for "unreferenced" functions

#include "../Common/GlobalDefines.h"
#include "JoystickDriver.c"
#include "Includes/TeamConfig.h"
#include "../Common/Control/ArmKinematics.h"
#include "../Common/Control/ArmControl.h"



task main()
{
	StartTask(ArmControlTask);
	servo[servo1] = 0;

	long g1 = ReadArmJointGoal(1);
	long g2 = ReadArmJointGoal(2);
	long g3 = ReadArmJointGoal(3);
	long g4 = ReadArmJointGoal(4);
	long g5 = ReadArmJointGoal(5);

	long a1 = ReadArmJointAngle(1);
	long a2 = ReadArmJointAngle(2);
	long a3 = ReadArmJointAngle(3);
	long a4 = ReadArmJointAngle(4);
	long a5 = ReadArmJointAngle(5);

	while (true)
	{
		if (joystick.joy1_y1 > 10)
		{
			ArmJoint_MoveToPosAtRate(1, ARM_J1_MAX_POS, 90.0);
		}
		else if (joystick.joy1_y1 < -10)
		{
			ArmJoint_MoveToPosAtRate(1, ARM_J1_MIN_POS, 90.0);
		}
		else
		{
			ArmJoint_Hold(1);
		}

		if (joystick.joy1_y2 > 10)
		{
			ArmJoint_MoveToPosAtRate(2, 960, 540.0);
		}
		else if (joystick.joy1_y2 < -10)
		{
			ArmJoint_MoveToPosAtRate(2, 10, 540.0);
		}
		else
		{
			ArmJoint_Hold(2);
		}

		if (joy1Btn(02))
		{
			servo[servo1] += 1;
		}
		else if (joy1Btn(04))
		{
			servo[servo1] -= 1;
		}
	}
}
