#pragma config(Sensor, S1,     GyroSensor,     sensorAnalogInactive)
#pragma config(Motor,  motorB,          driveMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          driveMotor,    tmotorNXT, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma systemFile            // this eliminates warning for "unreferenced" functions

#define TEAM_NUMBER 3717

#include "JoystickDriver.c"
#include "Includes/TeamConfig.h"
#include "../Common/GlobalDefines.h"
#include "../Common/Control/SensorTask.h"


///////////////////////////////////////////////////
task main
{
  bDisplayDiagnostics = false;

  eraseDisplay();

  StartTask(SensorTask);

  // simply loop displaying key gyro data
  while ( true )
  {
		float fElapsedTime = nPgmTime / 1000;
		string s = Gyro.bRotating ? "MOVE" : "HOLD";

		nxtDisplayTextLine(0, "%s - %4.2f secs", s, fElapsedTime);
		nxtDisplayTextLine(2, "bias: %4.2f", Gyro.fRotBias);
		nxtDisplayTextLine(4, "rot rate: %4.2f", Gyro.fDebiasedRotRate);
		nxtDisplayTextLine(5, "angle:    %4.2f", Gyro.fAngle);
  }
}
