#pragma config(Hubs,  S2, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S4, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S2_C1_1,     ArmJ2,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S2_C1_2,     ArmJ1,         tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S2_C2_1,     Turntable,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C2_2,     LeftDrive,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S4_C1_1,     Nothing,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C1_2,     RightDrive,    tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S4_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S4_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S4_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S4_C2_4,    servo4,               tServoStandard)
#pragma config(Servo,  srvo_S4_C2_5,    servo5,               tServoStandard)
#pragma config(Servo,  srvo_S4_C2_6,    servo6,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define TEAM_NUMBER 5076

#pragma systemFile            // this eliminates warning for "unreferenced" functions

#include "../Common/GlobalDefines.h"
#include "JoystickDriver.c"
#include "Includes/TeamConfig.h"
#include "../Common/Control/ArmKinematics.h"
#include "../Common/Control/ArmControl.h"

task main()
{
	while true()
	{
		ArmJoint_MoveToPosAtRate(1, ARM_J1_MIN_POS, 90.0);
	}
}
