#pragma config(Sensor, S1,     GyroSensor,     sensorAnalogInactive)
#pragma config(Motor,  motorA,          turnMotor,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          driveMotor,    tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          driveMotor,    tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define TEAM_NUMBER 3717

#include "JoystickDriver.c"
#include "Includes/TeamConfig.h"
#include "../Common/GlobalDefines.h"
#include "../Common/Control/SensorTask.h"

float calcJoystickAngle(int xaxis, int yaxis); //function prototypes
float calcTravelAngle(float joyAngle, float wheelAngle);
void turnSwerveSystem(float travelAngle);

float joyAngle = 0.0;
float travelAngle = 0.0;
float wheelAngle = 0.0;

int testVar = 0;

task main()
{
  eraseDisplay();
	nMotorEncoder[motorA] = 0;

  int yaxis = 0;
  int xaxis = 0;

  while (true) {
  	disableDiagnosticsDisplay();
  	getJoystickSettings(joystick);
	  yaxis = joystick.joy1_y1;
    xaxis = joystick.joy1_x1;

    //always have a wheelAngle range of 0 - 359. No negative values.
    if ((float)nMotorEncoder[motorA] < 0.0) {
    	wheelAngle = 360 + nMotorEncoder[motorA]/4.2;
    }
    else {
    	wheelAngle = (float)nMotorEncoder[motorA]/4.2;
    }

    joyAngle = calcJoystickAngle(xaxis, yaxis);
    travelAngle = calcTravelAngle(joyAngle, wheelAngle);
    turnSwerveSystem(travelAngle);
    nxtDisplayCenteredTextLine(2, "joyAngle: %4.2f", joyAngle);
    nxtDisplayCenteredTextLine(4, "whAngle: %4.2f", wheelAngle);
    nxtDisplayCenteredTextLine(6, "travAngle: %4.2f", travelAngle);
    nxtDisplayCenteredTextLine(7, "testVar: %4d", testVar);

    wait1Msec(10); //buffer for debugger console
	}
}

float calcJoystickAngle(int xaxis, int yaxis) {
  float angle;
	if(abs(yaxis) > 10 || abs(xaxis) > 10) { //threshold of 10
	  angle = atan(((float)yaxis/(float)xaxis));
	  angle = angle * (180.0/PI); //convert inherent radians to degrees
		if(yaxis >= 0 && xaxis >= 0) {
		  angle = 90.0 - abs(angle);
		}
		else if(yaxis <= 0 && xaxis >= 0) {
		  angle = abs(angle) + 90.0;
		}
		else if(yaxis <= 0 && xaxis <= 0) {
		  angle = 270.0 - abs(angle);
		}
		else if(yaxis >= 0 && xaxis <= 0) {
		  angle = abs(angle) + 270.0;
		}
	  return angle;
  }
  else {
    return 0;
  }
}

float calcTravelAngle(float joyAngle, float wheelAngle)
{
	float tD1 = joyAngle - wheelAngle;
	float tD2 = -(360 - tD1);
		if (abs(tD1) < abs(tD2)) {
			return tD1;
		}
		else {
			return tD2;
		}
	if (abs(tD1) == 180 || abs(tD2) == 180) {
		testVar = 1;
	}
}

void turnSwerveSystem(float travelAngle)
{
	if (abs(travelAngle) > 1) { //buffer zone of 1 degree
		if (travelAngle > 0) {
			motor[motorA] = abs(travelAngle)*5;
		}
		else {
			motor[motorA] = -abs(travelAngle)*5;
		}
	}
}
