#pragma config(Hubs,  S3, HTMotor,  HTMotor,  HTServo,  HTServo)
#pragma config(Hubs,  S4, HTMotor,  none,     none,     none)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S3_C1_1,     RRD,           tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S3_C1_2,     motorE,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S3_C2_1,     RFD,           tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S3_C2_2,     SPIN,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S4_C1_1,     LFD,           tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S4_C1_2,     LRD,           tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S3_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S3_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S3_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S3_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S3_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S3_C3_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S3_C4_1,    servo7,               tServoNone)
#pragma config(Servo,  srvo_S3_C4_2,    servo8,               tServoNone)
#pragma config(Servo,  srvo_S3_C4_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S3_C4_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S3_C4_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S3_C4_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define TEAM_NUMBER 3717

#include "Includes/TeamConfig.h"
#include "../Common/Autonomous Test.h"
