#pragma config(Hubs,   S1,              HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S2,              HTSmuxLo,            sensorI2CCustom)
#pragma config(Sensor, S3,              HTSmuxHi,            sensorI2CCustom)
#pragma config(Sensor, S4,              IRright,             sensorI2CCustom)
#pragma config(Motor,  motorA,          RightLight,          tmotorNormal, openLoop)
#pragma config(Motor,  motorB,          LeftLight,           tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     LeftUpperDrive,      tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     RightUpperDrive,     tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     ArmRotation,         tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     ArmElevation,        tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     LeftLowerDrive,      tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     RightLowerDrive,     tmotorNormal, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    RightBridge,         tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    LeftBridge,          tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    WristControl,        tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    ScoringShields,      tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    Right_Ski,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    Left_Ski,            tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define TEAM_NUMBER 3717

#include "..\Common\Autonomous Template.h"
#include "Includes\Right Bridge.h"
#include "Includes\Right Mountain.h"
#include "Includes\Right Dispense.h"
#include "Includes\Right Balance.h"
#include "Includes\Defense.h"
#include "Includes\Right Score.h"


////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////// TASK MAIN //////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
task main()
{
  int Mission = 1;  // 1 = Right Bridge, 2 = Right Mountain, 3 = Right Dispense, 4 = Right Balance, 5 = Defense

  InitializeRobot("RIGHT");		// Perform all required initialization sub-routines

  bDisplayDiagnostics = false;
  eraseDisplay();

  nxtDisplayCenteredBigTextLine(2, "Select");
  nxtDisplayCenteredBigTextLine(4, "Mission");

  wait1Msec(250);

  while ( nNxtButtonPressed != 3 )
  {
    if ( nNxtButtonPressed == 1 && time1[T1] > 500 && Mission < 6)
    {
      Mission++;
      time1[T1] = 0;
    }
    else if ( nNxtButtonPressed == 2 && time1[T1] > 500 && Mission > 1 )
    {
      Mission--;
      time1[T1] = 0;
    }

    if ( Mission == 1 )
    {
      nxtDisplayCenteredBigTextLine(2, "Right");
      nxtDisplayCenteredBigTextLine(4, "Score?");
    }
    else if ( Mission == 2 )
    {
      nxtDisplayCenteredBigTextLine(2, "Right");
      nxtDisplayCenteredBigTextLine(4, "Mountain?");
    }
    else if ( Mission == 3 )
    {
      nxtDisplayCenteredBigTextLine(2, "Right");
      nxtDisplayCenteredBigTextLine(4, "Dispense?");
    }
    else if ( Mission == 4 )
    {
      nxtDisplayCenteredBigTextLine(2, "Right");
      nxtDisplayCenteredBigTextLine(4, "Balance?");
    }
    else if ( Mission == 5 )
    {
      nxtDisplayCenteredBigTextLine(3, "Defense?");
    }
    else if ( Mission == 6 )
    {
      nxtDisplayCenteredBigTextLine(2, "Right");
      nxtDisplayCenteredBigTextLine(4, "Bridge?");
    }

    wait1Msec(25);
    eraseDisplay();
  }

  nxtDisplayCenteredBigTextLine(3, "CONFIRMED");

  wait1Msec(750);

  eraseDisplay();

  if ( Mission == 3 )
  {
    Right_Dispense();
    return;
  }
  else if ( Mission == 5 )
  {
    Defense();
    return;
  }
  else if ( Mission == 1 )
  {
    Right_Score();
    return;
  }

  bDisplayDiagnostics = true;

  waitForStart();

  if ( Mission == 6 )
  {
    Right_Bridge();
  }
  else if ( Mission == 2 )
  {
    Right_Mountain();
  }
  else if ( Mission == 4 )
  {
    Right_Balance();
  }
}
